services:
  backend:
    build: ./
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Niewiemjakiehaslo.!
      MYSQL_DATABASE: garden2
      MYSQL_USER: Piotr
      MYSQL_PASSWORD: HasloDatabase
    ports:
      - "3307:3306"
